language: node_js
node_js:
  - "11.10.1"
  
before_install:
  - gem install awesome_bot
  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - awesome_bot *.md --allow-redirect --white-list travis-ci,packagephobia.now
  - npm run ci

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

addons:
  code_climate:
    repo_token:
      secure: YV/BDthvyPdLeAYouWp2cnPE4go812R6A/1uPRw+ChJbcEUzbUx8GXXudNPmginz0HaSO7/dhz+GBxAnFe7atLVmRggC2BZHLUun4z2DEJXK+uGCRuUO08zGlZky7Sh9ScGcbki7w4w0tuHYXl/N3ym1VvVl+n6pSbHpe7oNv/7q/B48/SbYQg0Efxo8ozHCJx89P/5MOHknTqM85HIT/Ku0OadRp2tJjaUUnYxZgrNqtt0iYhxMQ2zI1jg9A+X1rYSt567QZDH0Eh8fEvdE5au5KLVyM+7n78K196USBys6ySxSeNtY5+mVScGPM7IB2QFUTNh9iA2cGTxRPmyYMDiHRRJUI2OT72JFEGVEdJwErbcU+mv/akt643NIOmr0gtHtdZye8JKINSRghpTIC0W2UhCgvMEU2CD7UwfR8Ouk56Vn8RDqFZCdcgnmeOvKzI2VUeo85b1wdgvPuZyS8fIWmCJHsWz2vVSSPmcZYKB9t4ies4cyFCScSsSr7CdKe5Rmvs1w1SO/cKo2GcAwThpr0tAAHXr3Iqd5y4AFfU2MeZDyikdtnGmPWLPzR5aonzDzsm3s32f4JhmV69/p9Cp/hv1OpGeZFlMxU5m/ZXMh90ctcDHbAn2OYYbW0MV/A8tNU6mema4oUDgwzSIMcNHrCey/yAq1KKGb5Dsn4R8=

env:
  global:
    - secure: n6Hvnz5mzvfxVAmeZPQHLIJ6kF/sHwV0AxvqelQQHsVKPJnWTGtlTeHKY336a3/3f+7jBFtwUVHbCIr9ImIU06mcXO38QLSbxej/DN0ezURNBSN7NYI3CG8DJ5vS3t+9icDugo1+vWrboWe5yPQb6nreQzpAu6nyYpxX6ExCKbu5A7NJuwjf6Zel9QAObhZyzhWiDzlZ6N6RsLvVMWMnQwKyPpY6CMDq8CWbLmKagPOWa61i4irCcezo5Ervgxo1MvEZ/1VN2Bw7E85Jz7GM0v5HBn9mjsskI05wnw231683icyD0AH4zZaVB2p3JhcNxyPrIfYiSld0ryPxOISejT+ftn/LWpDYgBSDs6Py1v+38M3UDMeGX6mmYbIA0l6O9I+jF/1WUCpjrSOSpm7BU1ric8Om8cHOrzqv0Rixeafay+I1hiqKf64hoFpHcKUV6EAjiZeu3qRmBL8BR31wETfZVyT45mmHQjv3xtr+5WX20cPMMCjhQOMQNHYoYr7XvEU5mJrEv1M1x4QEGyFzggoo6I+SLFF/GBjkabAp6ImE871y4s2zoxOFxjmMN0FsbFOkffmPCzHdPLCYhaaxki3bClcaoPty+XchaPDhoW+/WmQfSoG5n7MfXWBO1EmlUrZbIiXK0MRvYASbwRz9f4TrF4TaF/nlwDSVWTSq/dk=
