language: node_js
node_js:
  - node
before_install:
  - gem install awesome_bot
script:
  - awesome_bot **/*.md --allow-redirect --white-list travis-ci,packagephobia.now
  - npm run ci
env:
  global:
    secure: cNXHCm8EV19ztCT90hP3YtZvuHMVyK29pSdtNVtLAh3Mf17BX+VSyvCO2UHv8ZHHC7hCW9FecX4u1XaTw+MzOjkbYRTq9GdMJXHGDLZbT2G1x+azcl4vhrpVsiJ0VFyy+6LPiTrPh/h3O3tsVtFhRMrAg8CTvoudapqaUpVRiI8z903aTV6mXSMarB3kFR96BPik5kYvTgaodieFt9j+ikT/KWwdqstsGWtpmJ0J7M+fcB9TeFf5w1nPHEtGjhi1qpULMGMlh7DXbqDIRt0i6/KL/+mO0ggjeQB/Pwt0AxEpVlfUe63Ic2V2XaD3W6OQ4JMJIPN4G03grUqinnZya2SyEZCf5V1oOPbjABve3GvQuXYMG8DXD9cFLzZRBmILxHan4/TxZFMJ+8h4Fxt/RSa4oMPTzbamJCKaI93JL5ur97x9EaPMHhnnEp+7z5/p6U0kzogJxfCMp9kp7hEpbLWgMgNgYyvuGZWA30h96T/t5SdhRW9NmaM3KhBbJWsHcLHYyAN2zco++uMe4a4mWHDSOU9rdAMjwclCVIHKiZVch8pyuIpaNFqUK1Phq3lfdj3D5NV0reBp7D7HvIfrCJhhSXTqXLXbzr6UPpEg6/IRYIRdXfiQuqwk88yDzd8kKxHKZTedf5czaMNmFAsyLfjTiYhxszq6fW/J+PrD1BM=
